apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-kgun
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-kgun
    app.kubernetes.io/part-of: test-annotations-app-ldkw
  name: test-annotations-kgun
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-kgun
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-kgun
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-iuvv-tenant/test-annotations-app-ldkw/test-annotations-kgun@sha256:bfea9f8e7238d0555946059ae2e716596fb8c82702b2a345085cc5dcd4f4d364
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
